.TH "Helper::DateTime" 3 "Sun Apr 19 2020" "KeyLogger click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper::DateTime
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateTime\fP (int d, int m, int y, int H, int M, int S)"
.br
.ti -1c
.RI "\fBDateTime\fP (int d, int m, int y)"
.br
.ti -1c
.RI "\fBDateTime\fP \fBNow\fP () const"
.br
.ti -1c
.RI "std::string \fBgetDateString\fP () const"
.br
.ti -1c
.RI "std::string \fBgetTimeString\fP (const std::string &separator=':')"
.br
.ti -1c
.RI "std::string \fBgetDateTimeString\fP (const std::string &separator=':')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBd\fP"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBH\fP"
.br
.ti -1c
.RI "int \fBM\fP"
.br
.ti -1c
.RI "int \fBS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KeyLogger click from the source code\&.
