.TH "Keys" 3 "Sun Apr 19 2020" "KeyLogger click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keys
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::map< int, \fBKeyPair\fP > \fBKEYS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KeyLogger click from the source code\&.
